### ISSUE TITLE
Push/completion hooks (not sure what else to call them)

### ISSUE THREAD

**Issue by jknielse** [leanderlee/better-queue#2]
It'd be useful to have some kind of mechanism for running a function upon every push, and just before calling the callbacks for the completion of the associated items. Tracking the progress of items through a pipeline would be made easy by having queues that check in with a reporting system upon the addition and completion of items on the queue.

**Comment by leanderlee** [comment]
As of version 2, you can now listen on events; `task_accepted` when the task has been filtered, and `task_queued` when the task has been saved to the store for processing (but has not yet been processed)
